pushover:
  uri: https://api.pushover.net/1/messages.json
ngrok:
  baseUrl: ${NGROK_BASE_URL}

server:
  port: ${SERVER_PORT}
  error:
    whitelabel:
      enabled: false

application:
  client-origin-url: ${APPLICATION_CLIENT_ORIGIN_URL:''}
  disable-scheduler: ${APPLICATION_DISABLE_SCHEDULER:false}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    defer-datasource-initialization: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false