spring:
  config:
    activate:
      on-profile: local
  h2:
    # Access via: http://localhost:8080/h2-console
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:ytfeed
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
